### PR TITLE
Fix that allows running the plugin on Windows

### PR DESCRIPTION
**Pull request by rwicke**
I've made a small change to the Template class so that it uses the right file separator character instead of always using '/'. This was causing the plugin to fail on Windows.

### CODE REVIEW

**Comment by kevinbirch** [comment]
Thanks for this!  I really appreciate your submission, and I hope you've found the plug-in useful.

**Comment by rwicke** [comment]
Yes, I found the plugin very useful. I am using it for Java code generation (of classes for a StringTemplate-based code generator, ironically). Thanks for merging so quickly.

Any change you could cut a new release and publish to Central?

**Comment by kevinbirch** [comment]
I planning to try to push 1.1 this weekend. I'll let you know when it's done.

**Comment by rwicke** [comment]
That's great. Thanks!

-- Rob

**Comment by kevinbirch** [comment]
Since I'll be touching the code again, would either of these two features be useful to you?  (from the TODO file)
- support maven-style annotations in controller (e.g. annotate the method to invoke, the way to call c'tor, etc)
- support configuration element for controller (e.g. inject configuration from maven project state into controller)

I could roll these out with 1.1 if you're interested, or if there is another feature you would prefer please let me know.

**Comment by rwicke** [comment]
The existing plugin functionality is more than enough for my needs.

If you added annotation-based invocation, how would these custom annotations be packaged? You'd probably need a separate library for these so that controller code does not depend on the plugin artifact and its dependencies. While using annotations is more elegant, the added overall complexity may not justify them.

**Comment by kevinbirch** [comment]
I've just released version 1.1 of the plugin to maven central.  It takes some time for the uploads to synchronize with the central repo, but you should start seeing the new version within a couple of hours.  In addition to your change, I've also added support for properties at the controller level, and added a website (generated by Maven, there's a link in the README).

**Comment by rwicke** [comment]
Excellent! Tanks for that. I am planning a cut release of my project this weekend so this good timing.

-- Rob

**Pull request merged**
